Repository The-Day-In-1984/1984_Project, pull requests merged in 2023-05, with the labels that each got.

#108 Feat: Set climb direction
  1984/Assets/Scripts/Runtime/UI/Platformer/ClimbState.cs
Labels: enhancement, 프로그래밍

#109 Feat: Convert mutiple sheet(json)
  1984/Assets/Resources/Dialogue/Dialogue.xlsx
  1984/Assets/Resources/Dialogue/DialogueJson.json
  1984/Assets/Resources/Story.meta
  1984/Assets/Resources/Story/StoryData.xlsx
  1984/Assets/Resources/Story/StoryData.xlsx.meta
  1984/Assets/Resources/Story/StoryJson.json
  1984/Assets/Resources/Story/StoryJson.json.meta
  1984/Assets/Scripts/Editor/ExcelToJsonConverter.cs
  1984/Assets/Scripts/Runtime/Managers/DataManager.cs
  1984/Assets/Scripts/Runtime/Utils/Define.cs
  1984/Assets/Scripts/Runtime/Utils/JsonDataConverter.cs
Labels: enhancement

#139 Feature/misson system
  1984/Assets/Art/Sprites/Mission/Wine.png
  1984/Assets/Art/Sprites/Mission/Wine.png.meta
  1984/Assets/Resources/Prefabs/UI/Mission.meta
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_CigaretteCleaning.prefab
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_CigaretteCleaning.prefab.meta
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_EatingBread.prefab
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_EatingBread.prefab.meta
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_PouringWine.prefab
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_PouringWine.prefab.meta
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_Telephone.prefab
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_Telephone.prefab.meta
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_WritingDiary.prefab
  1984/Assets/Resources/Prefabs/UI/Mission/UIMission_WritingDiary.prefab.meta
  1984/Assets/Resources/Prefabs/UI/UIMission_Money.prefab
  1984/Assets/Scenes/JA/JAScene.unity
  1984/Assets/Scripts/Runtime/UI/Mission/Function/CountLogic.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Function/DistanceLogic.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Function/SpriteChanger.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Function/SpriteChanger.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/IMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/BaseMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/BaseMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/ClickMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/ClickMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/DragMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/DragMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/LogicMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/LogicMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/TimeMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/TimeMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/TriggerMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/Base/TriggerMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/BeginAndEndDragMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/BeginAndEndDragMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/ClickEventMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/ClickEventMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/ClickMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/DragMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/SameNumberLogicMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/SameNumberLogicMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/TriggerAlphaMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/TriggerAlphaMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/TriggerTimeMission.cs
  1984/Assets/Scripts/Runtime/UI/Mission/Mission/TriggerTimeMission.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController.cs
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/Base.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/Base/MissionController.cs
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/Base/MissionController.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/NoOrderFailMissionController.cs
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/NoOrderFailMissionController.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/NoOrderNotFailMissionController.cs
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/NoOrderNotFailMissionController.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/OrderNotFailMissionController.cs
  1984/Assets/Scripts/Runtime/UI/Mission/MissionController/OrderNotFailMissionController.cs.meta
  1984/Assets/Scripts/Runtime/UI/Mission/MissionView.cs
  1984/Assets/Scripts/Runtime/Utils/Define.cs
  1984/ProjectSettings/TagManager.asset
Labels: enhancement, 프로그래밍

#149 Fix: Init DIalogue
  1984/Assets/Resources/Prefabs/UI/UIView_Dialogue.prefab
  1984/Assets/Scripts/Runtime/UI/Dialogue/DialogueView.cs
  1984/Assets/Scripts/Runtime/UI/Dialogue/DialogueViewController.cs
Labels: bug, 프로그래밍

#150 Feat: Telescreen animation
  1984/Assets/Art/Sprites/Map/Day1_winstons_room.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room.png.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Bread.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Bread.png.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Cigar.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Cigar.png.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Diary.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Diary.png.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Drink.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Drink.png.meta
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Telephone.png
  1984/Assets/Art/Sprites/Map/Day1_winstons_room/winstons_room_Telephone.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen.meta
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother.png
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_EyeBrow.png
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_EyeBrow.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_Eyes_L.png
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_Eyes_L.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_Eyes_R.png
  1984/Assets/Art/Sprites/Map/Telescreen/BigBrother_Eyes_R.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_Backgound.png
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_Backgound.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_BigBrother.png
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_BigBrother.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_Loading_2.png
  1984/Assets/Art/Sprites/Map/Telescreen/Telescreen_Loading_2.png.meta
  1984/Assets/Art/Sprites/Map/Telescreen/telescreen_Loading_1.png
  1984/Assets/Art/Sprites/Map/Telescreen/telescreen_Loading_1.png.meta
  1984/Assets/Art/Sprites/Map/eye.png
  1984/Assets/Art/Sprites/Map/eye.png.meta
  1984/Assets/Scenes/MK/MKScene.unity
  1984/Assets/Scripts/Runtime/UI/Platformer/Telescreen/Telescreen.cs
  1984/Assets/Scripts/Runtime/UI/Platformer/Telescreen/TelescreenAnimationController.cs
  1984/Assets/Scripts/Runtime/UI/Platformer/Telescreen/TelescreenAnimationController.cs.meta
  1984/Assets/Scripts/Runtime/UI/Platformer/Telescreen/TelescreenEyes.cs
  1984/Assets/Scripts/Runtime/UI/Platformer/Telescreen/TelescreenEyes.cs.meta
Labels: 프로그래밍
